server:
  port: '8083'

spring:
  main:
    allow-circular-references: 'true'
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    url: jdbc:mysql://localhost:3306/project1
#    password: ''
    driver-class-name: oracle.jdbc.OracleDriver
    username: munna
    password: munna1234
    url: jdbc:oracle:thin:@localhost:1521:orcl

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
